# Database Connection Properties (Replace 'smartpcbuilderdb' with your actual schema name)
spring.datasource.url=jdbc:mysql://localhost:3306/smartpcbuilderdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD_HERE

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true